---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:0.4
spec:
  chartGitPath: podinfo
  releaseName: podinfo-prod
  values:
    image: stefanprodan/podinfo:0.3.0
    replicaCount: 3
